### ISSUE TITLE
dirscan联动问题

### ISSUE THREAD

**Issue by r00tit** [bit4woo/domain_hunter_pro#10]
没法改使用dirscan的参数，默认是Python37路径，可是我是别的路径就没法修改

**Comment by bit4woo** [comment]
这个已经修复，你可以重新clone最新代码，然后使用maven打包使用最新的更新。

```
git clone https://github.com/bit4woo/domain_hunter_pro
mvn package
```

**Comment by r00tit** [comment]
现在是联动了nmap，dirsearch，sqlmap，后面打不打算弄成自动定义联动其他工具

**Comment by bit4woo** [comment]
兼容所有其他工具的话，命令参数难以自定义，有的需要host、有的需要url、有的需要整改请求包还要自定义插入点。有好的思路欢迎交流。
