### ISSUE TITLE
师傅，titles功能有问题

### ISSUE THREAD

**Issue by Wwon1oung** [bit4woo/domain_hunter_pro#11]
如图所示：即使点击了停止也仍在跑，完全停不下来。。。

![image](https://user-images.githubusercontent.com/55070231/111567788-7de96480-87da-11eb-82a1-f6bdf8e89c2f.png)

并且titles里的内容还删除不掉，即使把域名设置为空，一直占用burp使用：

![image](https://user-images.githubusercontent.com/55070231/111567884-aa9d7c00-87da-11eb-96b0-ec85532ff9e7.png)

**Comment by bit4woo** [comment]
这个问题确实存在，多线程的处理方式导致的，目前简单的处理方法是：先remove掉插件后重新add。后续会考虑改进，感谢提issue
