### ISSUE TITLE
无法新增域名

### ISSUE THREAD

**Issue by wakaka123wakaka** [bit4woo/domain_hunter_pro#14]

**Comment by wakaka123wakaka** [comment]
![image](https://user-images.githubusercontent.com/34087959/113652960-6c072d00-96c7-11eb-87c9-3e013a0f5d7d.png)
![image](https://user-images.githubusercontent.com/34087959/113652988-77f2ef00-96c7-11eb-93c6-1b0d6d0c242d.png)

**Comment by bit4woo** [comment]
请查看 extender--->选中“Domain Hunter Pro”--->errors 中是否有错误信息，请提供
