### ISSUE TITLE
能不能实现个自动收集的，就不需要每次都点击search才收集域名

### ISSUE THREAD

**Issue by union-cmd** [bit4woo/domain_hunter_pro#20]
能不能实现个自动收集的，就不需要每次都点击search才收集域名

**Comment by bit4woo** [comment]
认真下文档和视频，就是自动收集的

**Comment by union-cmd** [comment]
是只要有流量进入proxy，那么就会自动收集到里面么，如果是这样的话，我这里实现不了的，我添加了根域名，流量也进了proxy，但是却没有添加到里面

**Comment by union-cmd** [comment]
我测了很多根域名，都不能自动添加到里面

**Comment by bit4woo** [comment]
![image](https://user-images.githubusercontent.com/8793481/129382611-3db084da-b3ca-4f88-9c2f-510ee4611a79.png)
点击刷新查看最新结果
