### ISSUE TITLE
有的网站标题是乱码

### ISSUE THREAD

**Issue by soapffz** [bit4woo/domain_hunter_pro#25]
有的网站标题是乱码 建议稍微优化下编码处理功能？
![image](https://user-images.githubusercontent.com/43143519/139537628-33ee2ef8-480d-4aa4-af4c-b55ac6f2aa94.png)

**Comment by bit4woo** [comment]
这和你的操作系统自身的编码有关系，建议系统本身的编码使用UTF-8

**Comment by soapffz** [comment]
Ok

**Comment by AlexANSO** [comment]
老哥 解决了吗？
