### ISSUE TITLE
自行编译问题之burp-api-common下载

### ISSUE THREAD

**Issue by soapffz** [bit4woo/domain_hunter_pro#27]
为什么自行编译中的burp-api-common一定要github认证了才可以下载，knife中的com.bit4woo.burp不是直接添加仓库就可以下载了吗？

![image](https://user-images.githubusercontent.com/43143519/140601418-de514251-d135-4e3e-9cd8-66c7c345438e.png)

本人项目管理小白，恳请讲解

**Comment by bit4woo** [comment]
这是因为这个依赖包是托管在GitHub的 package功能中的，配置方法在readme中有说明。
https://github.com/bit4woo/domain_hunter_pro/blob/master/README.md
