### ISSUE TITLE
问题反馈-get title没反应

### ISSUE THREAD

**Issue by soapffz** [bit4woo/domain_hunter_pro#28]
jdk版本：java 16.0.2
win10
经常搜集完域名后点击get title之后没反应，尤其在比较多的子域名的情况下更容易出现
有时候dashboard里的event log会跑日志，communicated failed
有时候啥都没有，也不请求
![image](https://user-images.githubusercontent.com/43143519/141646992-c0b7dc42-fcd8-4f28-9d39-487390401246.png)

![image](https://user-images.githubusercontent.com/43143519/141647047-fe6e9668-9a21-4ef1-ac5b-dd525802b575.png)

**Comment by soapffz** [comment]
1.4 release和最新版打包都是一样的情况

**Comment by bit4woo** [comment]
欢迎使用最新重构版本，如果还有问题欢迎再次提交，感谢！
https://github.com/bit4woo/domain_hunter_pro/releases/tag/v1.9-alpha
