### ISSUE TITLE
部分网站标题存在乱码情况

### ISSUE THREAD

**Issue by AlexANSO** [bit4woo/domain_hunter_pro#30]
一部分网站可以正常显示标题，但是还有一些无法显示
![image](https://user-images.githubusercontent.com/19631801/145938309-201c5701-56a1-47f4-8893-0d54f0b27123.png)
![image](https://user-images.githubusercontent.com/19631801/145938321-572d249f-be0c-419c-9e37-ab94b0d1b439.png)

已将系统语言改为utf-8
![image](https://user-images.githubusercontent.com/19631801/145938522-b7df7101-12e7-439e-8920-9bd9f83b9ef3.png)

并且报文中的中文显示正常，只有标题栏存在乱码

系统：Windows10
Burp：2021.8

**Comment by bit4woo** [comment]
https://github.com/bit4woo/domain_hunter_pro/commit/9f909d7f1aa18f6f5fd78b96b30f71337513d786 中做了部分加强，能大概率减少乱码出现，但是不能百分百解决所有问题。如果其他乱码情况出现，请提交具体URL以便进行分析。
