### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by H3ll0W0lrd** [bit4woo/domain_hunter_pro#35]
git 拉下来的源码编译错误，求指点。
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project domain_hunter_pro: Compilation failure
[ERROR] /Users/xxxx/Downloads/domain_hunter_pro-1.5/src/title/DirSearchAction.java:[8,12] cannot find symbol
[ERROR]   symbol:   class SystemUtils
[ERROR]   location: package burp

![image](https://user-images.githubusercontent.com/30374511/151219125-b22d9806-81c2-4860-b407-e95238786aa0.png)

**Comment by H3ll0W0lrd** [comment]
> git 拉下来的源码编译错误，求指点。 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project domain_hunter_pro: Compilation failure [ERROR] /Users/xxxx/Downloads/domain_hunter_pro-1.5/src/title/DirSearchAction.java:[8,12] cannot find symbol [ERROR] symbol: class SystemUtils [ERROR] location: package burp
> 
> ![image](https://user-images.githubusercontent.com/30374511/151219125-b22d9806-81c2-4860-b407-e95238786aa0.png)

已解决
得自己去burp-api-common项目把SysTEMutils放到burp下。
![image](https://user-images.githubusercontent.com/30374511/151529239-63b36242-463f-4b0b-b8d7-54fad7950d8f.png)

**Comment by x1aochuan** [comment]
👍
