### ISSUE TITLE
询问编译问题

### ISSUE THREAD

**Issue by GTX690** [bit4woo/domain_hunter_pro#36]
请问这个问题怎么解决？

![image](https://user-images.githubusercontent.com/38800368/156954858-615f8f53-f5f5-452d-8210-038e3ae04480.png)

`PS D:\softs\apache-maven-3.8.4\domain_hunter_pro-master> mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< com.bit4woo.burp:domain_hunter_pro >-----------------
[INFO] Building domain_hunter_pro v1.5
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.github.bit4woo:burp-api-common:jar:0.1.3 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.383 s
[INFO] Finished at: 2022-03-07T09:55:02+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project domain_hunter_pro: Could not resolve dependencies for project com.bit4woo.burp:domain_hunter_pro:jar:v1.5: com.github.bit4woo:burp-api-common:jar:0.1.3 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException`

**Comment by bit4woo** [comment]
请阅读 项目首页“自行打包使用最新功能”部分
