### ISSUE TITLE
【请教】获取Titles时遇到的问题

### ISSUE THREAD

**Issue by ifyoudo** [bit4woo/domain_hunter_pro#58]
在获取title时，所有结果的status都为-1。Title都为No DNS Record。这个问题要怎么解决。
![image](https://github.com/bit4woo/domain_hunter_pro/assets/48817407/d3a5c558-c132-4978-b57e-4ce2b3beaceb)

**Comment by bit4woo** [comment]
这种情况多半和你的网络环境有关，DNS解析失败

**Comment by BelloHe** [comment]
请问解决了吗？

**Comment by ifyoudo** [comment]
> 请问解决了吗？

没解决，网络环境没问题。你也遇到同样问题？
